
package com.review.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoPoemException", targetNamespace = "http://services.review.com/")
public class NoPoemException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoPoemException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoPoemException_Exception(String message, NoPoemException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoPoemException_Exception(String message, NoPoemException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.review.services.NoPoemException
     */
    public NoPoemException getFaultInfo() {
        return faultInfo;
    }

}
